// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>
using Yousource.Api.Extensions.Injection;

var builder = WebApplication.CreateBuilder(args);
var services = builder.Services;
var env = builder.Environment;

var configurationBuilder = new ConfigurationBuilder()
    .SetBasePath(env.ContentRootPath)
    .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: false, reloadOnChange: true)
    .AddEnvironmentVariables();

var configuration = configurationBuilder.Build();

// Add services to the container.

services.AddControllers();
services.AddApplicationInsightsTelemetry(configuration.GetSection("ApplicationInsights")["InstrumentationKey"]);

// Injection
services.ConfigureIdentity(configuration);
services.InjectInfrastructure(configuration);


var app = builder.Build();

// Configure the HTTP request pipeline.

if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
else
{
    app.UseHsts();
}

app.UseAuthentication();
app.UseRouting();

var allowedOrigins = configuration.GetSection("AllowedOrigins").Get<string[]>();
app.UseCors(cors => cors
    .WithOrigins(allowedOrigins)
    .AllowAnyMethod()
    .AllowAnyHeader());

app.UseAuthorization();

app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});

app.Run();
