# Use this .yml template to create a CI/build for You_Source ASP.NET Core 3.1 Project
# Each `env-ci.yml` will have different `trigger`
# By default, this `yml` publishes all `Web Apps` (e.g. APIs, Function Apps) in your solution,
# in your CD (release), pick projects to be deployed to intended Azure Resources

trigger:
- none

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'

steps:
- task: richardfennellBM.BM-VSTS-StyleCop-Task.Stylecop-Runner.StyleCop@3
  displayName: Yousource.Infrastructure
  inputs:
    sourcefolder: '$(build.SourcesDirectory)/Yousource.Infrastructure'
    settingsFile: '$(build.SourcesDirectory)/Yousource.Infrastructure/Settings.StyleCop'
- task: richardfennellBM.BM-VSTS-StyleCop-Task.Stylecop-Runner.StyleCop@3
  displayName: Yousource.Services.Identity
  inputs:
    sourcefolder: '$(build.SourcesDirectory)/Yousource.Services.Identity'
    settingsFile: '$(build.SourcesDirectory)/Yousource.Services.Identity/Settings.StyleCop'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: $(BuildParameters.TestProjects)
    arguments: --configuration $(BuildConfiguration) --collect "Code Coverage" --settings SolutionItems/CodeCoverage.runSettings
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.Yousource/*.Yousource.Api.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
  displayName: 'Publish Yousource API'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'


