trigger:
  - none
variables:
  - name: BuildParameters.RestoreBuildProjects
    value: "**/*.csproj"
  - name: BuildParameters.TestProjects
    value: "**/*[Tt]ests/*.csproj"
  - name: BuildConfiguration
    value: Release

name: $(date:yyyyMMdd)$(rev:.r)
jobs:
  - job: Job_1
    displayName: Agent job 1
    pool:
      vmImage: windows-2022
    steps:
      - checkout: self
      - task: richardfennellBM.BM-VSTS-StyleCop-Task.Stylecop-Runner.StyleCop@3
        displayName: Yousource.Infrastructure
        inputs:
          sourcefolder: '$(build.SourcesDirectory)/Yousource.Infrastructure'
          settingsFile: '$(build.SourcesDirectory)/Yousource.Infrastructure/Settings.StyleCop'
      - task: richardfennellBM.BM-VSTS-StyleCop-Task.Stylecop-Runner.StyleCop@3
        displayName: Yousource.Services.Identity
        inputs:
          sourcefolder: '$(build.SourcesDirectory)/Yousource.Services.Identity'
          settingsFile: '$(build.SourcesDirectory)/Yousource.Services.Identity/Settings.StyleCop'
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: $(BuildParameters.RestoreBuildProjects)
          arguments: --configuration $(BuildConfiguration)
      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          projects: $(BuildParameters.TestProjects)
          arguments: --configuration $(BuildConfiguration) --collect "Code Coverage" --settings SolutionItems/CodeCoverage.runSettings
